
services:
  - type: web
    name: housing-aggregator
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
    buildFilter:
      paths:
      - client/**
      - server/**
      - shared/**
    staticPublishPath: /opt/render/project/src/dist
