
services:
  - type: web
    name: housing-aggregator
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    staticPublishPath: ./dist
